# How many seconds before a TPA/TPAHERE request auto‐expires
request-timeout: 60

# How many seconds to count down once a request is accepted
countdown-seconds: 5

world-icons-enabled: true

# If world-icons are enabled, you can customize which Material shows for each world name:
world-icons:
  world:
    material: GRASS_BLOCK
    lore: "Overworld"
  world_nether:
    material: NETHERRACK
    lore: "Nether"
  world_the_end:
    material: END_STONE
    lore: "End"

# Disable tpa to players that flying or void'
safe-tpa: true

# Teleport cancel radius
cancel-move-radius: 2

# Cancel teleport on damage
cancel-on-damage: true